{
 "title": "VDBench",
 "tags": [ "vdbench" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Vdbench Single Stats (Current)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.resp" }
   ]
  },
  {
   "title": "Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.read_resp" }
   ]
  },
  {
   "title": "Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.write_resp" }
   ]
  },
  {
   "title": "Std Dev Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.resp_std" }
   ]
  },
  {
   "title": "Max Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.resp_max" }
   ]
  },
  {
   "title": "IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vdbench.default.*.rate" }
   ]
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(scale(vdbench.default.*.MBps, 1024), 1024)"
    }
   ]
  },
  {
   "title": "Transfer Size (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.iobytes" }
   ]
  },
  {
   "title": "Interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.interval" }
   ]
  },
  {
   "title": "Read Ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.readpct" }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "vdbench.default.*.compratio" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(vdbench.default.*.cpu_used, 'CPU Utilization')"
    }
   ]
  },
  { "title": "Vdbench Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Vdbench Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(vdbench.default.*.resptime, 'Latency')"
    },
    {
     "target": "alias(vdbench.default.*.read_resp, 'Read Latency')"
    },
    {
     "target": "alias(vdbench.default.*.write_resp, 'Write Latency')"
    }
   ]
  },
  {
   "title": "Vdbench IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(vdbench.default.*.iobytes, 'IOPS')"
    }
   ]
  },
  {
   "title": "Vdbench Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(scale(vdbench.default.*.MBps, 1024), 1024), 'Throughput')"
    }
   ]
  },
  {
   "title": "Vdbench Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(vdbench.default.*.queue_depth, 'Queue Depth')"
    },
    {
     "target": "alias(vdbench.default.*.cpu%sys+u, 'CPU')"
    }
   ]
  },
  {
   "title": "Vdbench Workload Definition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(vdbench.default.*.iobytes, 'Transfer Size')"
    },
    {
     "target": "alias(vdbench.default.*.readpct, 'Read Ratio')"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(vdbench.default.*.cpu_idle, 'CPU Idle')"
    },
    {
     "target": "alias(vdbench.default.*.cpu_kernel, 'CPU Kernel')"
    },
    {
     "target": "alias(vdbench.default.*.cpu_used, 'CPU Used')"
    },
    {
     "target": "alias(vdbench.default.*.cpu_user, 'CPU User')"
    },
    {
     "target": "alias(vdbench.default.*.cpu_wait, 'CPU Wait')"
    }
   ]
  }
 ]
}